Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,7 +56,7 @@ jobs:
           git clone --depth 1 https://github.com/altafyafai7/android_kernel_xiaomi_sky_upstream.git kernel/xiaomi/sky
           git clone --depth 1 https://github.com/Evolution-X-Devices/vendor_xiaomi_sky.git vendor/xiaomi/sky
 
-      - name: 🎩 EXPLICIT Magic Cross-Port Script (Deep Clean 3.0)
+      - name: 🎩 EXPLICIT Magic Cross-Port Script (Deep Clean 4.0)
         run: |
           cd ~/crdroid/device/xiaomi/sky
           rm -f vendorsetup.sh || true
@@ -87,6 +87,9 @@ jobs:
           
           echo "NUKING the Dolby error permanently..."
           grep -rl 'hardware/dolby/dolby.mk' . | xargs sed -i '/hardware\/dolby\/dolby.mk/d' || true
+          
+          echo "NUKING the BCR (Call Recorder) error permanently..."
+          grep -rl 'vendor/bcr/bcr.mk' . | xargs sed -i '/vendor\/bcr\/bcr.mk/d' || true
 
       - name: 🗑️ ULTIMATE SPACE HACK
         run: |
